sudo: required

env:
  - ARCH_TRAVIS_VERBOSE=1

language: c

compiler:
  - gcc
  - clang

arch:
  repos:
    - xyne-any=http://xyne.archlinux.ca/repos/xyne
    - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
    - reflector
    # aur
    - archey3-git
    # papyros
    - papyros-shell
  script:
    - "sudo archey3"
    - "reflector --verbose -l 20 --sort rate -p https"
    - "echo $CC"

script:
  - "bash ./arch-travis.sh"
